### ISSUE TITLE
Allow unauthorized client to create/paid the order by COD or store pickup

### ISSUE THREAD

**Issue by giangnguyen13** [giangnguyen13/comp_313_team6#31]

**Comment by franndyabreu** [comment]
What's the reason behind this? @giangnguyen13 . It is not secure to allow users that are not authorized to update the order table. For example, if I have your order ID I can make an API request to update your order attributes, even if im not you, which is not secure at all. Also, en every single product what matters is user data, that why we should always make them to sign up whenever possible.
